# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created: Fri Apr 20 01:49:13 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 865)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dspStartImage = QtGui.QGraphicsView(self.centralwidget)
        self.dspStartImage.setGeometry(QtCore.QRect(80, 40, 391, 311))
        self.dspStartImage.setObjectName("dspStartImage")
        self.dspEndImage = QtGui.QGraphicsView(self.centralwidget)
        self.dspEndImage.setGeometry(QtCore.QRect(640, 40, 381, 311))
        self.dspEndImage.setObjectName("dspEndImage")
        self.dspBlendedImage = QtGui.QGraphicsView(self.centralwidget)
        self.dspBlendedImage.setGeometry(QtCore.QRect(370, 410, 401, 311))
        self.dspBlendedImage.setObjectName("dspBlendedImage")
        self.btnLoadStart = QtGui.QPushButton(self.centralwidget)
        self.btnLoadStart.setGeometry(QtCore.QRect(80, 10, 161, 21))
        self.btnLoadStart.setObjectName("btnLoadStart")
        self.btnLoadEnding = QtGui.QPushButton(self.centralwidget)
        self.btnLoadEnding.setGeometry(QtCore.QRect(640, 10, 161, 21))
        self.btnLoadEnding.setObjectName("btnLoadEnding")
        self.sldAlpha = QtGui.QSlider(self.centralwidget)
        self.sldAlpha.setGeometry(QtCore.QRect(80, 380, 941, 20))
        self.sldAlpha.setMaximum(20)
        self.sldAlpha.setPageStep(1)
        self.sldAlpha.setTracking(False)
        self.sldAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sldAlpha.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sldAlpha.setTickInterval(2)
        self.sldAlpha.setObjectName("sldAlpha")
        self.btnBlend = QtGui.QPushButton(self.centralwidget)
        self.btnBlend.setGeometry(QtCore.QRect(520, 750, 92, 27))
        self.btnBlend.setObjectName("btnBlend")
        self.lblStartImage = QtGui.QLabel(self.centralwidget)
        self.lblStartImage.setGeometry(QtCore.QRect(220, 360, 101, 20))
        self.lblStartImage.setObjectName("lblStartImage")
        self.lblEndImage = QtGui.QLabel(self.centralwidget)
        self.lblEndImage.setGeometry(QtCore.QRect(780, 360, 91, 20))
        self.lblEndImage.setObjectName("lblEndImage")
        self.lblResult = QtGui.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(510, 720, 101, 20))
        self.lblResult.setObjectName("lblResult")
        self.lblAlpha = QtGui.QLabel(self.centralwidget)
        self.lblAlpha.setGeometry(QtCore.QRect(30, 380, 41, 17))
        self.lblAlpha.setObjectName("lblAlpha")
        self.lblAlphaMin = QtGui.QLabel(self.centralwidget)
        self.lblAlphaMin.setGeometry(QtCore.QRect(80, 400, 21, 16))
        self.lblAlphaMin.setObjectName("lblAlphaMin")
        self.lblAlphaMax = QtGui.QLabel(self.centralwidget)
        self.lblAlphaMax.setGeometry(QtCore.QRect(1000, 400, 21, 17))
        self.lblAlphaMax.setObjectName("lblAlphaMax")
        self.txtAlpha = QtGui.QLineEdit(self.centralwidget)
        self.txtAlpha.setGeometry(QtCore.QRect(1030, 380, 71, 21))
        self.txtAlpha.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAlpha.setObjectName("txtAlpha")
        self.chkTriangles = QtGui.QCheckBox(self.centralwidget)
        self.chkTriangles.setGeometry(QtCore.QRect(500, 340, 121, 21))
        self.chkTriangles.setObjectName("chkTriangles")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadStart.setText(QtGui.QApplication.translate("MainWindow", "Load Starting Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadEnding.setText(QtGui.QApplication.translate("MainWindow", "Load Ending Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlend.setText(QtGui.QApplication.translate("MainWindow", "Blend", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartImage.setText(QtGui.QApplication.translate("MainWindow", "Starting Image", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndImage.setText(QtGui.QApplication.translate("MainWindow", "Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.lblResult.setText(QtGui.QApplication.translate("MainWindow", "Blending Result", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAlpha.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAlphaMin.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAlphaMax.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTriangles.setText(QtGui.QApplication.translate("MainWindow", "Show Triangles", None, QtGui.QApplication.UnicodeUTF8))

